name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

  run-tests:
    runs-on: ubuntu-latest
    needs: setup-environment
    steps:
      - name: Run Unit Tests
        run: |
          pytest --maxfail=5 --disable-warnings
      - name: Security Checks
        run: |
          pip install bandit pip-audit
          bandit -r .
          pip-audit

  packaging:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Build Package
        run: |
          python setup.py sdist
